// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import edu.wpi.first.wpilibj.Joystick;
import frc.robot.subsystems.*;
import edu.wpi.first.wpilibj.ADIS16470_IMU;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();

// Subsystems
public final Lift m_lift = new Lift();
public final Dumper m_dumper = new Dumper();
public final Intake m_intake = new Intake();
public final DriveTrain m_driveTrain = new DriveTrain();
// Joysticks
private final Joystick arcadeJoystick = new Joystick(2);
private final Joystick rightTankJoystick = new Joystick(1);
private final Joystick leftTankJoystick = new Joystick(0);
// Commands
private final ArcadeDrive m_ArcadeDrive = new ArcadeDrive(m_driveTrain, arcadeJoystick);
private final TankDrive m_TankDrive = new TankDrive(m_driveTrain, leftTankJoystick, rightTankJoystick);
// Command Getters
public ArcadeDrive getArcadeDrive(){ return m_ArcadeDrive; }
public TankDrive getTankDrive(){ return m_TankDrive;}
// Gyro
public static final ADIS16470_IMU gyro = new ADIS16470_IMU();


  
  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
  * The container for the robot.  Contains subsystems, OI devices, and commands.
  */
  private RobotContainer() {
  
    // Smartdashboard Subsystems
      

    // SmartDashboard Buttons
   /*
   SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
    SmartDashboard.putData("TankDrive", new TankDrive( m_driveTrain ));
    SmartDashboard.putData("Dump", new Dump( m_dumper ));
    SmartDashboard.putData("Climb", new Climb( m_lift ));
    SmartDashboard.putData("IntakeRise", new IntakeRise( m_intake ));
    SmartDashboard.putData("IntakeSpin", new IntakeSpin( m_intake ));
*/
   
    // Configure the button bindings
    configureButtonBindings();
        

    // Configure autonomous sendable chooser
    m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

    //SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings.  Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
        
// Create some buttons
final JoystickButton arcadeTrigger = new JoystickButton(arcadeJoystick, 0);        
arcadeTrigger.whenPressed(new Climb( m_lift ) ,true);

final JoystickButton rightTrigger = new JoystickButton(rightTankJoystick, 0);        
rightTrigger.whenHeld(new Dump( m_dumper ) ,true);

final JoystickButton leftTrigger = new JoystickButton(leftTankJoystick, 0);        
leftTrigger.whenHeld(new IntakeSpin( m_intake ) ,true);
   
final JoystickButton arcadeLeftUpStick = new JoystickButton(arcadeJoystick, 1);
arcadeLeftUpStick.whenHeld(new IntakeRise(m_intake) ,true);

final JoystickButton arcadeLeftDownStick = new JoystickButton(arcadeJoystick, 2);
arcadeLeftDownStick.whenHeld(new IntakeRise(m_intake) ,true);


  }

    
public Joystick getLeftTankJoystick() {
        return leftTankJoystick;
    }

public Joystick getRightTankJoystick() {
        return rightTankJoystick;
    }

public Joystick getArcadeJoystick() {
        return arcadeJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
  */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
  

}

